language: generic
services: docker
script:
  - docker run --volume=$(pwd):/app --workdir=/app coala/base:pre /bin/bash -c "pip3 install 'git+https://github.com/jayvdb/coala-quickstart@gh_39'; coala-quickstart --ci; coala-ci"
